export const SAIT = [
    {   
        id:1,
        img:require("./pictures/sait1.jpg"),
        alt: "SAIT1",
    },
    {
        id:2,
        img:require("./pictures/sait2.jpg"),
        alt:"SAIT2",
    },
    {
        id:3,
        img:require("./pictures/sait3.jpg"),
        alt:"SAIT3",
    },
    {
        id:4,
        img:require("./pictures/sait4.jpg"),
        alt:"SAIT4",
    },
    {
        id:5,
        img:require("./pictures/sait5.jpg"),
        alt:"SAIT5",
    }
];

export const Google= [
    {
        id:1,
        img:require("./pictures/google1.jpg"),
        alt:"Google1",
    },
    {
        id:2,
        img:require("./pictures/google2.jpg"),
        alt:"Google2",
    },
    {
        id:3,
        img:require("./pictures/google3.jpg"),
        alt:"Google3",
    },
    {
        id:4,
        img:require("./pictures/google4.jpg"),
        alt:"Google4",
    },
    {
        id:5,
        img:require("./pictures/google5.jpg"),
        alt:"Google5",
    }
];

export const WorkingHoliday = [
    {
        id:1,
        img:require("./pictures/wh1.jpg"),
        alt:"WH1",
    },
    {
        id:2,
        img:require("./pictures/wh2.jpg"),
        alt:"WH2",
    },
    {
        id:3,
        img:require("./pictures/wh3.jpg"),
        alt:"WH3",
    },
    {
        id:4,
        img:require("./pictures/wh4.jpg"),
        alt:"WH4",
    },
    {
        id:5,
        img:require("./pictures/wh5.jpg"),
        alt:"WH5",
    },
    {
        id:6,
        img:require("./pictures/wh6.jpg"),
        alt:"WH6",
    },
    {
        id:7,
        img:require("./pictures/wh7.jpg"),
        alt:"WH7",
    },
    {
        id:8,
        img:require("./pictures/wh8.jpg"),
        alt:"WH8",
    },
    {
        id:9,
        img:require("./pictures/wh9.jpg"),
        alt:"WH9",
    },
    {
        id:10,
        img:require("./pictures/wh10.jpg"),
        alt:"WH10",
    },
    {
        id:11,
        img:require("./pictures/wh11.jpg"),
        alt:"WH11",
    }
];

export const Dietitian = [
    {
        id:1,
        img:require("./pictures/dietitian1.jpg"),
        alt:"Dietitian1",
    },
    {
        id:2,
        img:require("./pictures/dietitian2.jpg"),
        alt:"Dietitian2",
    },
    {
        id:3,
        img:require("./pictures/dietitian3.jpg"),
        alt:"Dietitian3",
    },
    {
        id:4,
        img:require("./pictures/dietitian4.jpg"),
        alt:"Dietitian4",
    }
];
